import assert from 'node:assert/strict'
import test from 'node:test'
import { bmi, bmiCategory, compoundSavings, dateDifference, healthyWeightRange, loanAmortization, percentageCalculation, roi, vat, weekdaysBetween } from './calculations'
test('compound savings separates contributions and interest', () => { const result = compoundSavings(1000, 12, 12, 100); assert.ok(result.total > result.contributed); assert.equal(result.schedule.length, 12); assert.equal(result.contributed, 2200) })
test('loan schedule pays down exactly', () => { const result = loanAmortization(12000, 12, 12); assert.equal(result.schedule.length, 12); assert.ok(Math.abs(result.schedule.at(-1)!.balance) < .000001); assert.ok(result.totalInterest > 0) })
test('calendar difference preserves leap birthday fields', () => { const result = dateDifference('2000-02-29', '2024-02-29'); assert.equal(result.years, 24); assert.equal(result.remainingMonths, 0) })
test('roi deflates nominal return', () => { assert.equal(Math.round(roi(100, 120, 10).realPercent * 100) / 100, 9.09) })
test('vat remove reverses add', () => { assert.deepEqual(vat(120, 20, 'remove'), { net: 100, tax: 20, gross: 120 }) })
test('bmi is calculated from metric units', () => { assert.equal(Math.round(bmi(180, 81) * 10) / 10, 25) })
test('percentage modes cover share, change, increase, decrease and ratio', () => { assert.equal(percentageCalculation('of', 200, 25).result, 50); assert.equal(percentageCalculation('change', 80, 100).result, 25); assert.ok(Math.abs(percentageCalculation('increase', 100, 10).result - 110) < 1e-9); assert.equal(percentageCalculation('decrease', 100, 10).result, 90); assert.equal(percentageCalculation('ratio', 50, 200).result, 25); assert.equal(percentageCalculation('change', 0, 5).valid, false); assert.equal(percentageCalculation('ratio', 5, 0).valid, false) })
test('weekday counting excludes weekends and tolerates reversed dates', () => { assert.equal(weekdaysBetween('2024-01-01', '2024-01-08'), 5); assert.equal(weekdaysBetween('2024-01-08', '2024-01-01'), 5); assert.equal(weekdaysBetween('2024-01-06', '2024-01-08'), 0); assert.equal(weekdaysBetween('bad', '2024-01-08'), 0) })
test('bmi categories and healthy range follow WHO thresholds', () => { assert.equal(bmiCategory(18.4), 'underweight'); assert.equal(bmiCategory(24.9), 'normal'); assert.equal(bmiCategory(29.9), 'overweight'); assert.equal(bmiCategory(30), 'obese'); const range = healthyWeightRange(180); assert.ok(range.min > 59 && range.min < 60.1); assert.ok(range.max > 80 && range.max < 81); assert.deepEqual(healthyWeightRange(0), { min: 0, max: 0 }) })
