/**
 * An original four-dimension preference inventory in the Jungian / Myers-Briggs tradition.
 * 32 bipolar items (8 per dimension) on a five-point scale, following the structure of open
 * research instruments such as the Open Extended Jungian Type Scales. It is a reflection tool:
 * type inventories show modest test–retest reliability, and preferences are continuous, so
 * results are reported with a strength and clarity band rather than as a fixed label.
 */
import type { Language } from './format'

export type Dimension = 'EI' | 'SN' | 'TF' | 'JP'
export type Letter = 'E' | 'I' | 'S' | 'N' | 'T' | 'F' | 'J' | 'P'
/** 1 = strongly the left statement … 5 = strongly the right statement. */
export type Response = 1 | 2 | 3 | 4 | 5
export type Clarity = 'balanced' | 'slight' | 'moderate' | 'clear' | 'veryClear'
type Localized = Record<Language, string>
const L = (tr: string, en: string, ru: string): Localized => ({ tr, en, ru })
export type Item = { id: number; dimension: Dimension; /** Letter expressed by the left statement. */ left: Letter; leftText: Localized; rightText: Localized }

export const DIMENSIONS: readonly Dimension[] = ['EI', 'SN', 'TF', 'JP']
export const PAIRS: Readonly<Record<Dimension, readonly [Letter, Letter]>> = { EI: ['E', 'I'], SN: ['S', 'N'], TF: ['T', 'F'], JP: ['J', 'P'] }
export const ITEMS_PER_DIMENSION = 8
export const MAX_SCORE = ITEMS_PER_DIMENSION * 2
export const PAGE_SIZE = 8

const item = (id: number, dimension: Dimension, left: Letter, leftText: Localized, rightText: Localized): Item => ({ id, dimension, left, leftText, rightText })

/** Items alternate which pole sits on the left so a habit of picking one side does not bias a dimension. */
export const ITEMS: readonly Item[] = [
  item(1, 'EI', 'E', { tr: 'Kalabalık bir ortamda enerjim yükselir.', en: 'A busy, social setting raises my energy.', ru: 'Оживлённая компания заряжает меня энергией.' }, { tr: 'Kalabalık bir ortam bir süre sonra beni yorar.', en: 'A busy, social setting tires me after a while.', ru: 'Оживлённая компания через какое-то время меня утомляет.' }),
  item(2, 'SN', 'N', { tr: 'Yeni bir fikrin nereye gidebileceğini hayal etmek beni heyecanlandırır.', en: 'Imagining where a new idea could lead excites me.', ru: 'Меня захватывает представлять, куда может привести новая идея.' }, { tr: 'Bir fikrin şu an nasıl işe yarayacağını görmek beni heyecanlandırır.', en: 'Seeing how an idea works in practice right now excites me.', ru: 'Меня захватывает видеть, как идея работает на практике прямо сейчас.' }),
  item(3, 'TF', 'F', { tr: 'Bir karar verirken önce insanların nasıl hissedeceğini düşünürüm.', en: 'When deciding, I first think about how people will feel.', ru: 'Принимая решение, я сначала думаю о том, что почувствуют люди.' }, { tr: 'Bir karar verirken önce neyin mantıklı olduğunu düşünürüm.', en: 'When deciding, I first think about what is logical.', ru: 'Принимая решение, я сначала думаю о том, что логично.' }),
  item(4, 'JP', 'J', { tr: 'Gün planımı önceden yapmak beni rahatlatır.', en: 'Planning my day in advance puts me at ease.', ru: 'Мне спокойнее, когда день спланирован заранее.' }, { tr: 'Günün akışına göre karar vermek beni rahatlatır.', en: 'Deciding as the day unfolds puts me at ease.', ru: 'Мне спокойнее решать по ходу дня.' }),
  item(5, 'EI', 'I', { tr: 'Düşüncelerimi paylaşmadan önce içimde olgunlaştırırım.', en: 'I let ideas mature privately before sharing them.', ru: 'Я даю идеям созреть про себя, прежде чем делиться.' }, { tr: 'Düşüncelerimi konuşarak netleştiririm.', en: 'I clarify ideas by talking them through.', ru: 'Я проясняю идеи, проговаривая их вслух.' }),
  item(6, 'SN', 'S', { tr: 'Öğrenirken somut örnekler ve adım adım yönergeler isterim.', en: 'When learning, I want concrete examples and step-by-step instructions.', ru: 'Обучаясь, я хочу конкретные примеры и пошаговые инструкции.' }, { tr: 'Öğrenirken önce genel ilkeyi kavrayıp ayrıntıyı sonra doldururum.', en: 'When learning, I grasp the principle first and fill in details later.', ru: 'Обучаясь, я сначала схватываю принцип, а детали дополняю потом.' }),
  item(7, 'TF', 'T', { tr: 'Doğrudan ve açık eleştiri bana yardımcı olur.', en: 'Direct, blunt criticism helps me.', ru: 'Прямая, откровенная критика мне помогает.' }, { tr: 'Eleştirinin nazikçe ifade edilmesi bana yardımcı olur.', en: 'Criticism helps me when it is delivered gently.', ru: 'Критика помогает мне, когда её подают мягко.' }),
  item(8, 'JP', 'P', { tr: 'Seçenekleri son ana kadar açık tutmayı severim.', en: 'I like keeping my options open until the last moment.', ru: 'Мне нравится держать варианты открытыми до последнего момента.' }, { tr: 'Kararı verip konuyu kapatmayı severim.', en: 'I like deciding and closing the matter.', ru: 'Мне нравится принять решение и закрыть вопрос.' }),
  item(9, 'EI', 'E', { tr: 'Yeni insanlarla tanışmak bana kolay gelir.', en: 'Meeting new people comes easily to me.', ru: 'Знакомиться с новыми людьми мне легко.' }, { tr: 'Yeni insanlarla tanışmak için biraz ısınmam gerekir.', en: 'I need some time to warm up before meeting new people.', ru: 'Перед знакомством с новыми людьми мне нужно немного освоиться.' }),
  item(10, 'SN', 'N', { tr: 'Bir hikâyede sembolleri ve gizli anlamları fark ederim.', en: 'In a story, I notice symbols and hidden meanings.', ru: 'В истории я замечаю символы и скрытые смыслы.' }, { tr: 'Bir hikâyede olayları ve ayrıntıları fark ederim.', en: 'In a story, I notice the events and the details.', ru: 'В истории я замечаю события и детали.' }),
  item(11, 'TF', 'F', { tr: 'Bir tartışmada herkesin duyulmuş hissetmesi sonuçtan önemlidir.', en: 'In a debate, everyone feeling heard matters more than the outcome.', ru: 'В споре важнее, чтобы каждый почувствовал себя услышанным, чем результат.' }, { tr: 'Bir tartışmada doğru sonuca ulaşmak duygulardan önemlidir.', en: 'In a debate, reaching the right conclusion matters more than feelings.', ru: 'В споре важнее прийти к верному выводу, чем чувства.' }),
  item(12, 'JP', 'J', { tr: 'Bir işi son teslim tarihinden çok önce bitiririm.', en: 'I finish work well before the deadline.', ru: 'Я заканчиваю работу задолго до дедлайна.' }, { tr: 'Bir işi son teslim tarihine yakın bitirmek beni motive eder.', en: 'Finishing close to the deadline motivates me.', ru: 'Меня мотивирует заканчивать ближе к дедлайну.' }),
  item(13, 'EI', 'I', { tr: 'Uzun bir sosyal günün ardından yalnız kalarak toparlanırım.', en: 'After a long social day I recover by being alone.', ru: 'После долгого дня общения я восстанавливаюсь в одиночестве.' }, { tr: 'Uzun bir sosyal günün ardından bile başka insanlarla görüşmek isterim.', en: 'Even after a long social day I still want to see other people.', ru: 'Даже после долгого дня общения мне хочется увидеть других людей.' }),
  item(14, 'SN', 'S', { tr: 'Daha önce işe yaramış yöntemlere güvenirim.', en: 'I trust methods that have worked before.', ru: 'Я доверяю методам, которые уже работали.' }, { tr: 'Denenmemiş yeni yaklaşımları merak ederim.', en: 'I am curious about untried new approaches.', ru: 'Мне любопытны новые, ещё не опробованные подходы.' }),
  item(15, 'TF', 'T', { tr: 'Adalet herkes için aynı kuralı uygulamaktır.', en: 'Fairness means applying the same rule to everyone.', ru: 'Справедливость — это одно правило для всех.' }, { tr: 'Adalet herkesin koşulunu dikkate almaktır.', en: 'Fairness means considering each person’s circumstances.', ru: 'Справедливость — это учёт обстоятельств каждого.' }),
  item(16, 'JP', 'P', { tr: 'Programsız, spontane bir tatil bana daha çekici gelir.', en: 'An unplanned, spontaneous holiday appeals to me more.', ru: 'Незапланированный спонтанный отпуск привлекает меня больше.' }, { tr: 'Programı önceden yapılmış bir tatil bana daha çekici gelir.', en: 'A holiday with a set itinerary appeals to me more.', ru: 'Отпуск с готовым маршрутом привлекает меня больше.' }),
  item(17, 'EI', 'E', { tr: 'Bir grupta konuşmayı ben başlatırım.', en: 'In a group, I am the one who starts the conversation.', ru: 'В группе я тот, кто начинает разговор.' }, { tr: 'Bir grupta konuşmanın bana gelmesini beklerim.', en: 'In a group, I wait for the conversation to come to me.', ru: 'В группе я жду, пока разговор дойдёт до меня.' }),
  item(18, 'SN', 'N', { tr: 'Zihnim sık sık geleceğe ve olasılıklara kayar.', en: 'My mind often drifts to the future and to possibilities.', ru: 'Мои мысли часто уносятся в будущее и возможности.' }, { tr: 'Zihnim çoğunlukla şu anda olup bitende kalır.', en: 'My mind mostly stays with what is happening now.', ru: 'Мои мысли в основном остаются с тем, что происходит сейчас.' }),
  item(19, 'TF', 'F', { tr: 'Sorun çözerken duygular önemli bir bilgidir.', en: 'When solving a problem, feelings are important information.', ru: 'Решая проблему, я считаю чувства важной информацией.' }, { tr: 'Sorun çözerken duyguları geçici olarak kenara koyabilirim.', en: 'When solving a problem, I can set feelings aside for a while.', ru: 'Решая проблему, я могу на время отложить чувства.' }),
  item(20, 'JP', 'J', { tr: 'Masamın ve dosyalarımın düzenli olması işimi kolaylaştırır.', en: 'A tidy desk and organized files make my work easier.', ru: 'Порядок на столе и в файлах облегчает мне работу.' }, { tr: 'Aradığımı bulduğum sürece düzen benim için ikincildir.', en: 'As long as I can find what I need, order is secondary.', ru: 'Пока я нахожу нужное, порядок для меня вторичен.' }),
  item(21, 'EI', 'I', { tr: 'Az sayıda derin dostluk bana yeter.', en: 'A few deep friendships are enough for me.', ru: 'Мне достаточно нескольких глубоких дружб.' }, { tr: 'Geniş bir arkadaş çevresi bana iyi gelir.', en: 'A wide circle of friends is good for me.', ru: 'Мне хорошо с широким кругом друзей.' }),
  item(22, 'SN', 'S', { tr: 'Bir şeyi anlatırken ayrıntıları atlamamaya özen gösteririm.', en: 'When explaining, I take care not to skip details.', ru: 'Объясняя, я стараюсь не пропускать детали.' }, { tr: 'Bir şeyi anlatırken ana fikri verip ayrıntıyı kısa keserim.', en: 'When explaining, I give the main idea and keep details short.', ru: 'Объясняя, я даю главную мысль и сокращаю детали.' }),
  item(23, 'TF', 'T', { tr: 'Bir planı güçlü ve zayıf yanlarını listeleyerek değerlendiririm.', en: 'I evaluate a plan by listing its strengths and weaknesses.', ru: 'Я оцениваю план, перечисляя его сильные и слабые стороны.' }, { tr: 'Bir planı insanların ihtiyaçlarına uyup uymadığına bakarak değerlendiririm.', en: 'I evaluate a plan by whether it fits people’s needs.', ru: 'Я оцениваю план по тому, подходит ли он людям.' }),
  item(24, 'JP', 'P', { tr: 'Yapılacaklar listesi beni kısıtlanmış hissettirir.', en: 'A to-do list makes me feel constrained.', ru: 'Список дел вызывает у меня чувство ограничения.' }, { tr: 'Yapılacaklar listesi beni odaklar.', en: 'A to-do list keeps me focused.', ru: 'Список дел помогает мне держать фокус.' }),
  item(25, 'EI', 'E', { tr: 'Bir sorunla karşılaşınca hemen birinin fikrini almak isterim.', en: 'When I hit a problem, I want someone’s input right away.', ru: 'Столкнувшись с проблемой, я сразу хочу узнать чьё-то мнение.' }, { tr: 'Bir sorunla karşılaşınca önce kendi başıma çözmeyi denerim.', en: 'When I hit a problem, I first try to solve it on my own.', ru: 'Столкнувшись с проблемой, я сначала пробую решить её сам.' }),
  item(26, 'SN', 'N', { tr: 'Bir projede ileride doğabilecek fırsatlar beni cezbeder.', en: 'In a project, the opportunities that may appear later attract me.', ru: 'В проекте меня привлекают возможности, которые могут появиться позже.' }, { tr: 'Bir projede hemen görülebilir, ölçülebilir sonuçlar beni cezbeder.', en: 'In a project, results that are visible and measurable now attract me.', ru: 'В проекте меня привлекают результаты, видимые и измеримые сейчас.' }),
  item(27, 'TF', 'F', { tr: 'Birini incitmemek için sözlerimi yumuşatırım.', en: 'I soften my words so I do not hurt anyone.', ru: 'Я смягчаю слова, чтобы никого не задеть.' }, { tr: 'Açık olmak için sözlerimi yumuşatmam.', en: 'I do not soften my words; clarity comes first.', ru: 'Я не смягчаю слова — важнее ясность.' }),
  item(28, 'JP', 'J', { tr: 'Karar verdikten sonra hemen uygulamaya geçmek isterim.', en: 'Once I decide, I want to move into action.', ru: 'Приняв решение, я хочу сразу действовать.' }, { tr: 'Karar verdikten sonra bile yeni bilgiye açık kalırım.', en: 'Even after deciding, I stay open to new information.', ru: 'Даже после решения я остаюсь открытым к новой информации.' }),
  item(29, 'EI', 'I', { tr: 'Sessiz bir akşam benim için ideal dinlenmedir.', en: 'A quiet evening is my ideal way to rest.', ru: 'Тихий вечер — мой идеальный отдых.' }, { tr: 'Hareketli bir akşam benim için ideal dinlenmedir.', en: 'A lively evening is my ideal way to rest.', ru: 'Оживлённый вечер — мой идеальный отдых.' }),
  item(30, 'SN', 'S', { tr: 'Talimatları olduğu gibi uygulamak bana güven verir.', en: 'Following instructions as written gives me confidence.', ru: 'Следование инструкции как написано придаёт мне уверенности.' }, { tr: 'Talimatın amacını anlayıp kendi yolumu bulmayı tercih ederim.', en: 'I prefer understanding the goal and finding my own way.', ru: 'Я предпочитаю понять цель и найти свой путь.' }),
  item(31, 'TF', 'T', { tr: 'Haklı olmaktansa doğru olmak benim için önemlidir.', en: 'Being correct matters more to me than being liked.', ru: 'Быть правым для меня важнее, чем нравиться.' }, { tr: 'Doğru olmaktansa ilişkiyi korumak benim için önemlidir.', en: 'Preserving the relationship matters more to me than being correct.', ru: 'Сохранить отношения для меня важнее, чем быть правым.' }),
  item(32, 'JP', 'P', { tr: 'Son dakika değişiklikleri beni pek rahatsız etmez.', en: 'Last-minute changes do not bother me much.', ru: 'Изменения в последний момент меня не особо беспокоят.' }, { tr: 'Son dakika değişiklikleri beni rahatsız eder.', en: 'Last-minute changes bother me.', ru: 'Изменения в последний момент меня беспокоят.' }),
]

export function isResponse(value: unknown): value is Response {
  return value === 1 || value === 2 || value === 3 || value === 4 || value === 5
}

/** Rebuilds a response sheet from untrusted JSON; anything that is not 1–5 stays unanswered. */
export function normalizeResponses(value: unknown, length = ITEMS.length): (Response | undefined)[] {
  const list = Array.isArray(value) ? value : []
  return Array.from({ length }, (_, index) => (isResponse(list[index]) ? list[index] : undefined))
}

export function serializeResponses(responses: readonly (Response | undefined)[]) {
  return JSON.stringify(responses.map((response) => (isResponse(response) ? response : null)))
}

export function clarityFor(score: number): Clarity {
  const strength = Math.abs(score)
  if (strength === 0) return 'balanced'
  if (strength <= 3) return 'slight'
  if (strength <= 8) return 'moderate'
  if (strength <= 12) return 'clear'
  return 'veryClear'
}

export type DimensionScore = {
  dimension: Dimension
  letters: readonly [Letter, Letter]
  /** −16 … +16; positive favours the first letter of the pair. */
  score: number
  /** 0 … 100, how strongly the leaning letter is preferred. */
  strength: number
  /** 0 … 100 share of the pair going to the first letter, for symmetric bars. */
  firstShare: number
  leaning: Letter | null
  clarity: Clarity
  answered: number
}
export type PersonalityResult = {
  answered: number
  total: number
  complete: boolean
  dimensions: DimensionScore[]
  /** Four letters, or null while a dimension is exactly balanced. */
  type: string | null
  /** Four characters with X for a balanced dimension. */
  pattern: string
  possibleTypes: string[]
}

export function scoreResponses(responses: readonly (Response | undefined)[], items: readonly Item[] = ITEMS): PersonalityResult {
  const dimensions = DIMENSIONS.map((dimension): DimensionScore => {
    const letters = PAIRS[dimension]
    let score = 0
    let answered = 0
    items.forEach((entry, index) => {
      if (entry.dimension !== dimension) return
      const response = responses[index]
      if (!isResponse(response)) return
      answered += 1
      const towardsLeft = 3 - response
      score += entry.left === letters[0] ? towardsLeft : -towardsLeft
    })
    const leaning = score === 0 ? null : score > 0 ? letters[0] : letters[1]
    return { dimension, letters, score, strength: Math.round((Math.abs(score) / MAX_SCORE) * 100), firstShare: Math.round(((score + MAX_SCORE) / (2 * MAX_SCORE)) * 100), leaning, clarity: clarityFor(score), answered }
  })
  const pattern = dimensions.map((dimension) => dimension.leaning ?? 'X').join('')
  const possibleTypes = dimensions.reduce<string[]>((types, dimension) => types.flatMap((prefix) => (dimension.leaning ? [prefix + dimension.leaning] : dimension.letters.map((letter) => prefix + letter))), [''])
  const answered = responses.filter(isResponse).length
  return { answered, total: items.length, complete: answered === items.length, dimensions, type: pattern.includes('X') ? null : pattern, pattern, possibleTypes }
}

/** Types that differ from `type` in exactly one letter, ordered by the weakest preference first. */
export function neighbouringTypes(result: PersonalityResult): string[] {
  if (!result.type) return []
  return [...result.dimensions]
    .sort((a, b) => Math.abs(a.score) - Math.abs(b.score))
    .map((dimension) => result.type!.split('').map((letter, index) => (DIMENSIONS[index] === dimension.dimension ? (dimension.letters[0] === letter ? dimension.letters[1] : dimension.letters[0]) : letter)).join(''))
}

export const DIMENSION_QUESTIONS: Readonly<Record<Dimension, Localized>> = {
  EI: L('Enerjini nereden alırsın?', 'Where does your energy come from?', 'Откуда вы берёте энергию?'),
  SN: L('Bilgiyi nasıl alırsın?', 'How do you take in information?', 'Как вы воспринимаете информацию?'),
  TF: L('Nasıl karar verirsin?', 'How do you make decisions?', 'Как вы принимаете решения?'),
  JP: L('Dış dünyayı nasıl düzenlersin?', 'How do you organise your outer world?', 'Как вы организуете внешний мир?'),
}

export type LetterProfile = { title: Localized; summary: Localized; signs: Localized }
export const LETTERS: Readonly<Record<Letter, LetterProfile>> = {
  E: { title: { tr: 'Dışadönüklük', en: 'Extraversion', ru: 'Экстраверсия' }, summary: { tr: 'Enerjini insanlarla ve dış dünyayla etkileşimden alırsın; düşüncelerini konuşarak netleştirirsin.', en: 'You draw energy from people and the outer world, and you clarify ideas by talking them through.', ru: 'Вы черпаете энергию из общения и внешнего мира и проясняете идеи, проговаривая их.' }, signs: { tr: 'Geniş çevre, hızlı tepki, yüksek sesle düşünme', en: 'Wide circle, quick responses, thinking out loud', ru: 'Широкий круг, быстрые реакции, мышление вслух' } },
  I: { title: { tr: 'İçedönüklük', en: 'Introversion', ru: 'Интроверсия' }, summary: { tr: 'Enerjini iç dünyandan alırsın; önce düşünüp sonra paylaşmayı ve derin, seçici bağları tercih edersin.', en: 'You draw energy from your inner world, prefer reflecting before sharing, and favour deep, selective bonds.', ru: 'Вы черпаете энергию из внутреннего мира, предпочитаете сначала подумать, а потом делиться, и цените глубокие избирательные связи.' }, signs: { tr: 'Derin dostluklar, yalnız kalarak toparlanma, önce dinleme', en: 'Deep friendships, recharging alone, listening first', ru: 'Глубокая дружба, восстановление в одиночестве, сначала слушать' } },
  S: { title: { tr: 'Duyumsama', en: 'Sensing', ru: 'Сенсорика' }, summary: { tr: 'Somut gerçeklere, ayrıntılara ve kanıtlanmış deneyime güvenirsin; bugünü olduğu gibi görürsün.', en: 'You trust concrete facts, details and proven experience, and you see the present as it is.', ru: 'Вы доверяете конкретным фактам, деталям и проверенному опыту и видите настоящее таким, какое оно есть.' }, signs: { tr: 'Adım adım yönergeler, pratik sonuçlar, gözlem gücü', en: 'Step-by-step instructions, practical results, strong observation', ru: 'Пошаговые инструкции, практические результаты, наблюдательность' } },
  N: { title: { tr: 'Sezgi', en: 'Intuition', ru: 'Интуиция' }, summary: { tr: 'Örüntülere, olasılıklara ve büyük resme odaklanırsın; “ne olabilir” sorusu seni harekete geçirir.', en: 'You focus on patterns, possibilities and the big picture; “what could be” moves you.', ru: 'Вы сосредоточены на закономерностях, возможностях и общей картине; вопрос «что могло бы быть» движет вами.' }, signs: { tr: 'Gelecek odaklı fikirler, metaforlar, yeni yaklaşımlar', en: 'Future-oriented ideas, metaphors, novel approaches', ru: 'Идеи о будущем, метафоры, новые подходы' } },
  T: { title: { tr: 'Düşünme', en: 'Thinking', ru: 'Мышление' }, summary: { tr: 'Kararlarında tutarlılık, mantık ve nesnel ölçütler öne çıkar; doğrudan geri bildirimi tercih edersin.', en: 'Consistency, logic and objective criteria lead your decisions, and you prefer direct feedback.', ru: 'Ваши решения ведут последовательность, логика и объективные критерии; вы предпочитаете прямую обратную связь.' }, signs: { tr: 'Artı–eksi listeleri, açık eleştiri, aynı kural herkese', en: 'Pros-and-cons lists, candid critique, the same rule for everyone', ru: 'Списки за и против, откровенная критика, одно правило для всех' } },
  F: { title: { tr: 'Hissetme', en: 'Feeling', ru: 'Чувство' }, summary: { tr: 'Kararlarında insanlar üzerindeki etki ve değerler öne çıkar; uyumu ve karşılıklı anlayışı korumaya çalışırsın.', en: 'The impact on people and shared values lead your decisions, and you work to keep harmony and understanding.', ru: 'Ваши решения ведут влияние на людей и общие ценности; вы стараетесь сохранять гармонию и взаимопонимание.' }, signs: { tr: 'Nazik geri bildirim, empati, duruma göre adalet', en: 'Gentle feedback, empathy, case-by-case fairness', ru: 'Мягкая обратная связь, эмпатия, справедливость по ситуации' } },
  J: { title: { tr: 'Yargılama', en: 'Judging', ru: 'Суждение' }, summary: { tr: 'Plan, kapanış ve düzen sana güven verir; kararı verip uygulamaya geçmeyi seversin.', en: 'Plans, closure and order give you confidence; you like to decide and move into action.', ru: 'Планы, завершённость и порядок дают вам уверенность; вам нравится решить и перейти к действию.' }, signs: { tr: 'Erken bitirme, düzenli masa, yapılacaklar listesi', en: 'Finishing early, a tidy desk, to-do lists', ru: 'Заканчивать заранее, порядок на столе, списки дел' } },
  P: { title: { tr: 'Algılama', en: 'Perceiving', ru: 'Восприятие' }, summary: { tr: 'Seçenekleri açık tutmak ve akışa uyum sağlamak sana esneklik verir; yeni bilgiye kapıyı geç kapatırsın.', en: 'Keeping options open and adapting to the flow gives you flexibility; you close the door to new information late.', ru: 'Открытые варианты и адаптация к потоку дают вам гибкость; вы поздно закрываете дверь для новой информации.' }, signs: { tr: 'Spontane planlar, son dakika enerjisi, esneklik', en: 'Spontaneous plans, last-minute energy, flexibility', ru: 'Спонтанные планы, энергия последнего момента, гибкость' } },
}

export type TypeProfile = { title: Localized; summary: Localized; strengths: Localized[]; growth: Localized[]; work: Localized; relationships: Localized }
export const TYPES: Readonly<Record<string, TypeProfile>> = {
  ISTJ: { title: L('Güvenilir uygulayıcı', 'Dependable implementer', 'Надёжный исполнитель'), summary: L('Sorumluluğu ciddiye alır, kanıtlanmış yöntemlerle ve düzenli adımlarla ilerlersin. Sözünün arkasında durman ve ayrıntıya gösterdiğin özen çevrende güven yaratır.', 'You take responsibility seriously and move in orderly steps using proven methods. Keeping your word and caring about details earns you trust.', 'Вы серьёзно относитесь к ответственности и движетесь упорядоченными шагами, используя проверенные методы. Верность слову и внимание к деталям вызывают доверие.'), strengths: [L('Tutarlılık ve disiplin', 'Consistency and discipline', 'Последовательность и дисциплина'), L('Ayrıntıya hâkimiyet', 'Command of detail', 'Владение деталями'), L('Sakin, güvenilir duruş', 'Calm, reliable presence', 'Спокойная надёжность')], growth: [L('Değişime daha erken açılmak', 'Opening up to change sooner', 'Раньше открываться переменам'), L('Duyguları da veri olarak görmek', 'Treating feelings as information too', 'Считать чувства тоже информацией'), L('Mükemmeliyetçiliği gevşetmek', 'Loosening perfectionism', 'Ослабить перфекционизм')], work: L('Net süreçler, ölçülebilir hedefler ve tutarlı kurallar olan işlerde parlarsın.', 'You shine in roles with clear processes, measurable goals and consistent rules.', 'Вы сильны в ролях с чёткими процессами, измеримыми целями и последовательными правилами.'), relationships: L('Sadakat ve eylemle sevgi gösterirsin; duyguları sözle ifade etmek biraz pratik ister.', 'You show love through loyalty and action; putting feelings into words takes practice.', 'Вы показываете любовь верностью и делом; выражать чувства словами требует практики.') },
  ISFJ: { title: L('Özenli destekçi', 'Considerate supporter', 'Заботливая опора'), summary: L('İnsanların ihtiyaçlarını fark eder, sessizce ama istikrarlı biçimde destek olursun. Geleneklere ve pratik ayrıntılara verdiğin önem seni güvenilir kılar.', 'You notice what people need and support them quietly and steadily. Your respect for tradition and practical detail makes you reliable.', 'Вы замечаете, что нужно людям, и поддерживаете их тихо и стабильно. Уважение к традициям и практическим деталям делает вас надёжным.'), strengths: [L('Sıcak ve pratik yardımseverlik', 'Warm, practical helpfulness', 'Тёплая практическая помощь'), L('Güçlü hafıza ve dikkat', 'Strong memory and attention', 'Хорошая память и внимание'), L('Sabır', 'Patience', 'Терпение')], growth: [L('Kendi ihtiyaçlarını da dile getirmek', 'Voicing your own needs too', 'Озвучивать и свои потребности'), L('Hayır diyebilmek', 'Learning to say no', 'Учиться говорить «нет»'), L('Belirsizliği tolere etmek', 'Tolerating uncertainty', 'Переносить неопределённость')], work: L('İnsanlara doğrudan fayda sağlayan, düzenli ve sakin ortamlarda verimli olursun.', 'You are productive in orderly, calm settings where your work directly helps people.', 'Вы продуктивны в упорядоченной спокойной обстановке, где ваша работа напрямую помогает людям.'), relationships: L('Şefkatli ve bağlısın; takdir edilmek senin için çok değerlidir.', 'You are caring and devoted; being appreciated means a great deal to you.', 'Вы заботливы и преданы; признательность значит для вас очень много.') },
  INFJ: { title: L('Sezgili idealist', 'Insightful idealist', 'Проницательный идеалист'), summary: L('İnsanların ardındaki anlamı okur, uzun vadeli bir vizyonla ve derin değerlerle hareket edersin. Az ama derin bağlar kurmayı seçersin.', 'You read the meaning behind people and act on a long-term vision and deep values. You choose few but deep connections.', 'Вы читаете смысл за людьми и действуете из долгосрочного видения и глубоких ценностей. Вы выбираете немногие, но глубокие связи.'), strengths: [L('Derin empati ve içgörü', 'Deep empathy and insight', 'Глубокая эмпатия и проницательность'), L('Anlam ve amaç odağı', 'Focus on meaning and purpose', 'Фокус на смысле и цели'), L('Sessiz kararlılık', 'Quiet determination', 'Тихая решимость')], growth: [L('Aşırı idealizmi dengelemek', 'Balancing high ideals', 'Уравновешивать высокие идеалы'), L('Tükenmeden önce dinlenmek', 'Resting before burnout', 'Отдыхать до выгорания'), L('Eleştiriyi kişisel almamak', 'Not taking criticism personally', 'Не принимать критику на свой счёт')], work: L('İnsanların gelişimine ve anlamlı bir amaca hizmet eden işlerde motive olursun.', 'You are motivated by work that serves people’s growth and a meaningful purpose.', 'Вас мотивирует работа, служащая развитию людей и значимой цели.'), relationships: L('Derin, sahici bağlar ararsın; yüzeysel ilişkiler seni yorar.', 'You seek deep, authentic bonds; superficial relationships drain you.', 'Вы ищете глубокие подлинные связи; поверхностные отношения вас истощают.') },
  INTJ: { title: L('Stratejik planlayıcı', 'Strategic planner', 'Стратег'), summary: L('Karmaşık sistemleri kavrar ve uzun vadeli planlar kurarsın. Bağımsız düşünür, yüksek standartlarla ve mantıkla ilerlersin.', 'You grasp complex systems and build long-term plans. You think independently and move with logic and high standards.', 'Вы схватываете сложные системы и строите долгосрочные планы. Вы мыслите независимо и движетесь с логикой и высокими стандартами.'), strengths: [L('Uzun vadeli strateji', 'Long-range strategy', 'Долгосрочная стратегия'), L('Bağımsız, özgün düşünce', 'Independent, original thinking', 'Независимое оригинальное мышление'), L('Yüksek standartlar', 'High standards', 'Высокие стандарты')], growth: [L('Sabırsızlığı yönetmek', 'Managing impatience', 'Управлять нетерпением'), L('Duyguların yerini tanımak', 'Recognising the place of emotions', 'Признавать место эмоций'), L('Fikirleri erken paylaşmak', 'Sharing ideas earlier', 'Раньше делиться идеями')], work: L('Özerklik, zorlayıcı problemler ve net bir vizyon sunan işlerde en iyisini verirsin.', 'You do your best work with autonomy, hard problems and a clear vision.', 'Лучше всего вы работаете при автономии, сложных задачах и ясном видении.'), relationships: L('Az sayıda derin ve entelektüel bağ kurarsın; güven zamanla oluşur.', 'You form a few deep, intellectual bonds; trust builds over time.', 'Вы создаёте немногие глубокие интеллектуальные связи; доверие строится со временем.') },
  ISTP: { title: L('Pratik çözücü', 'Practical troubleshooter', 'Практичный мастер'), summary: L('Sorunları elinle ve gözlemle çözer, kriz anında sakin kalırsın. Özgürlüğüne düşkün, gereksiz kuraldan uzak durursun.', 'You solve problems hands-on through observation and stay calm in a crisis. You value freedom and avoid needless rules.', 'Вы решаете проблемы руками и наблюдением и сохраняете спокойствие в кризис. Вы цените свободу и избегаете лишних правил.'), strengths: [L('Kriz anında soğukkanlılık', 'Composure under pressure', 'Хладнокровие под давлением'), L('Mekanik ve pratik zekâ', 'Mechanical, practical intelligence', 'Механический практический ум'), L('Verimlilik', 'Efficiency', 'Эффективность')], growth: [L('Uzun vadeli taahhütler', 'Long-term commitments', 'Долгосрочные обязательства'), L('Duyguları paylaşmak', 'Sharing feelings', 'Делиться чувствами'), L('Rutini sürdürmek', 'Sustaining routine', 'Поддерживать рутину')], work: L('Somut, teknik ve bağımsız çalışılan işlerde parlarsın.', 'You shine in concrete, technical and independent work.', 'Вы сильны в конкретной, технической и самостоятельной работе.'), relationships: L('Sakin, sadık ve az sözlüsün; eylemle var olursun.', 'You are calm, loyal and sparing with words; you show up through action.', 'Вы спокойны, верны и немногословны; вы проявляете себя действием.') },
  ISFP: { title: L('Sessiz sanatçı', 'Quiet artist', 'Тихий художник'), summary: L('Anı yaşar, estetiğe ve kişisel değerlere önem verirsin. Nazik ve uyumlu tavrınla insanlara alan tanırsın.', 'You live in the moment and value aesthetics and personal values. Your gentle, easygoing manner gives people space.', 'Вы живёте моментом и цените эстетику и личные ценности. Ваша мягкая, лёгкая манера даёт людям пространство.'), strengths: [L('Estetik duyarlılık', 'Aesthetic sensitivity', 'Эстетическая чуткость'), L('Nazik ve kabul edici tavır', 'Gentle, accepting manner', 'Мягкая принимающая манера'), L('Uyum sağlama', 'Adaptability', 'Адаптивность')], growth: [L('Uzun vadeli planlama', 'Long-term planning', 'Долгосрочное планирование'), L('Çatışmadan kaçmamak', 'Not avoiding conflict', 'Не избегать конфликтов'), L('Kendini ifade etmek', 'Speaking up for yourself', 'Отстаивать себя')], work: L('Yaratıcı, insana dokunan ve baskısız ortamlarda verimli olursun.', 'You are productive in creative, people-centred, low-pressure settings.', 'Вы продуктивны в творческой, ориентированной на людей обстановке без давления.'), relationships: L('Sıcak ve sadıksın; sevgiyi küçük jestlerle gösterirsin.', 'You are warm and loyal; you show love through small gestures.', 'Вы тёплый и верный человек; любовь проявляете небольшими жестами.') },
  INFP: { title: L('Değer odaklı hayalperest', 'Values-driven dreamer', 'Мечтатель с ценностями'), summary: L('İçsel değerlerin pusulandır; anlam ve özgünlük ararsın. Yaratıcı, empatik ve kendi ritminde ilerleyen birisin.', 'Your inner values are your compass; you seek meaning and authenticity. You are creative, empathetic and move at your own pace.', 'Ваш компас — внутренние ценности; вы ищете смысл и подлинность. Вы креативны, эмпатичны и движетесь в своём темпе.'), strengths: [L('Derin empati', 'Deep empathy', 'Глубокая эмпатия'), L('Yaratıcılık ve hayal gücü', 'Creativity and imagination', 'Творчество и воображение'), L('Değerlere sadakat', 'Loyalty to values', 'Верность ценностям')], growth: [L('Fikirleri eyleme dökmek', 'Turning ideas into action', 'Превращать идеи в действия'), L('Eleştiriye dayanıklılık', 'Resilience to criticism', 'Устойчивость к критике'), L('Pratik ayrıntılar', 'Practical details', 'Практические детали')], work: L('Anlamlı bir amacı olan, esnek ve yaratıcı işlerde motive olursun.', 'You are motivated by flexible, creative work with a meaningful purpose.', 'Вас мотивирует гибкая творческая работа со значимой целью.'), relationships: L('Sahicilik ve derinlik ararsın; anlaşıldığını hissetmek seni besler.', 'You seek authenticity and depth; feeling understood nourishes you.', 'Вы ищете подлинность и глубину; чувство, что вас понимают, питает вас.') },
  INTP: { title: L('Meraklı analist', 'Curious analyst', 'Любознательный аналитик'), summary: L('Fikirleri parçalarına ayırıp mantıksal tutarlılık ararsın. Bağımsız çalışmayı ve karmaşık problemleri seversin.', 'You take ideas apart and look for logical consistency. You enjoy independent work and complex problems.', 'Вы разбираете идеи на части и ищете логическую последовательность. Вам нравятся самостоятельная работа и сложные задачи.'), strengths: [L('Analitik derinlik', 'Analytical depth', 'Аналитическая глубина'), L('Özgün problem çözme', 'Original problem solving', 'Оригинальное решение задач'), L('Entelektüel merak', 'Intellectual curiosity', 'Интеллектуальное любопытство')], growth: [L('Projeleri tamamlamak', 'Finishing projects', 'Доводить проекты до конца'), L('Duygusal ihtiyaçları fark etmek', 'Noticing emotional needs', 'Замечать эмоциональные потребности'), L('Pratik rutinler', 'Practical routines', 'Практические рутины')], work: L('Teori, sistem tasarımı ve özerklik sunan işlerde parlarsın.', 'You shine in work involving theory, system design and autonomy.', 'Вы сильны в работе с теорией, проектированием систем и автономией.'), relationships: L('Zihinsel uyum ararsın; sevgini paylaşılan fikirlerle gösterirsin.', 'You seek intellectual rapport; you show affection through shared ideas.', 'Вы ищете интеллектуальное созвучие; привязанность проявляете через общие идеи.') },
  ESTP: { title: L('Enerjik pragmatist', 'Energetic pragmatist', 'Энергичный прагматик'), summary: L('Anlık fırsatları görür ve harekete geçersin. Risk almaktan çekinmez, somut sonuçları ve hareketi seversin.', 'You spot immediate opportunities and act. You are comfortable with risk and love concrete results and motion.', 'Вы замечаете сиюминутные возможности и действуете. Вам комфортно с риском, вы любите конкретные результаты и движение.'), strengths: [L('Hızlı karar ve eylem', 'Fast decisions and action', 'Быстрые решения и действия'), L('Kriz yönetimi', 'Crisis handling', 'Управление кризисами'), L('İkna gücü', 'Persuasiveness', 'Убедительность')], growth: [L('Uzun vadeli sonuçları düşünmek', 'Weighing long-term consequences', 'Взвешивать долгосрочные последствия'), L('Sabır', 'Patience', 'Терпение'), L('Duygulara alan açmak', 'Making room for feelings', 'Оставлять место чувствам')], work: L('Hareketli, sonuç odaklı ve insanlarla iç içe işlerde verimli olursun.', 'You are productive in fast, results-driven, people-facing work.', 'Вы продуктивны в быстрой, ориентированной на результат работе с людьми.'), relationships: L('Eğlenceli ve cömertsin; derinlik için yavaşlamak gerekir.', 'You are fun and generous; depth requires slowing down.', 'Вы весёлый и щедрый; для глубины нужно замедлиться.') },
  ESFP: { title: L('Neşeli eğlendirici', 'Joyful entertainer', 'Радостный артист'), summary: L('İnsanlarla birlikteyken parlar, anı dolu dolu yaşarsın. Sıcaklığın ve spontanlığın ortamı canlandırır.', 'You shine around people and live the moment fully. Your warmth and spontaneity light up a room.', 'Вы сияете среди людей и живёте моментом сполна. Ваши тепло и спонтанность оживляют любую компанию.'), strengths: [L('Sosyal sıcaklık', 'Social warmth', 'Социальное тепло'), L('Pratik yardımseverlik', 'Practical helpfulness', 'Практическая отзывчивость'), L('Uyum ve esneklik', 'Adaptability', 'Адаптивность')], growth: [L('Uzun vadeli planlama', 'Long-term planning', 'Долгосрочное планирование'), L('Eleştiriyi taşımak', 'Handling criticism', 'Переносить критику'), L('Sıkıcı işleri bitirmek', 'Finishing tedious tasks', 'Заканчивать скучные дела')], work: L('İnsanlarla iletişim, hareket ve çeşitlilik içeren işlerde parlarsın.', 'You shine in work with people contact, movement and variety.', 'Вы сильны в работе с общением, движением и разнообразием.'), relationships: L('Cömert ve eğlencelisin; takdir ve paylaşılan deneyim seni besler.', 'You are generous and fun; appreciation and shared experiences nourish you.', 'Вы щедры и веселы; признательность и общие впечатления питают вас.') },
  ENFP: { title: L('İlham veren kâşif', 'Inspiring explorer', 'Вдохновляющий исследователь'), summary: L('Yeni fikirler ve insanlar seni heyecanlandırır. Coşkunla başkalarını da harekete geçirir, olasılıklarla oynamayı seversin.', 'New ideas and people excite you. Your enthusiasm moves others, and you love playing with possibilities.', 'Новые идеи и люди воодушевляют вас. Ваш энтузиазм движет другими, и вы любите играть с возможностями.'), strengths: [L('Coşku ve ilham', 'Enthusiasm and inspiration', 'Энтузиазм и вдохновение'), L('İnsanları okuma', 'Reading people', 'Понимание людей'), L('Yaratıcı bağlantılar', 'Creative connections', 'Творческие связи')], growth: [L('Odağı korumak', 'Sustaining focus', 'Удерживать фокус'), L('Projeleri tamamlamak', 'Finishing projects', 'Доводить проекты до конца'), L('Aşırı taahhütten kaçınmak', 'Avoiding over-commitment', 'Избегать перегрузки обязательствами')], work: L('Çeşitlilik, insan ve yaratıcılık sunan işlerde motive olursun.', 'You are motivated by work with variety, people and creativity.', 'Вас мотивирует работа с разнообразием, людьми и творчеством.'), relationships: L('Sıcak ve ilgilisin; özgürlük ve derin sohbet seni besler.', 'You are warm and attentive; freedom and deep conversation nourish you.', 'Вы тёплый и внимательный; свобода и глубокий разговор питают вас.') },
  ENTP: { title: L('Yenilikçi tartışmacı', 'Inventive debater', 'Изобретательный спорщик'), summary: L('Fikirleri sınamayı, alışılmışa meydan okumayı seversin. Hızlı düşünür, zekice çözümler üretirsin.', 'You enjoy testing ideas and challenging convention. You think fast and produce clever solutions.', 'Вам нравится проверять идеи и бросать вызов привычному. Вы быстро мыслите и находите остроумные решения.'), strengths: [L('Hızlı, esnek zekâ', 'Quick, flexible mind', 'Быстрый гибкий ум'), L('Yenilikçi bakış', 'Innovative outlook', 'Новаторский взгляд'), L('Tartışma yeteneği', 'Debating skill', 'Умение спорить')], growth: [L('Takip ve tamamlama', 'Follow-through', 'Доведение до конца'), L('Başkalarının hassasiyetleri', 'Others’ sensitivities', 'Чувствительность других'), L('Rutini kabullenmek', 'Accepting routine', 'Принятие рутины')], work: L('Belirsiz problemler, yeni ürünler ve özgür tartışma ortamlarında parlarsın.', 'You shine with open problems, new products and free debate.', 'Вы сильны в открытых задачах, новых продуктах и свободных дискуссиях.'), relationships: L('Zihinsel uyarım ararsın; sevgini espri ve fikir alışverişiyle gösterirsin.', 'You seek mental stimulation; you show affection through wit and exchange of ideas.', 'Вы ищете умственную стимуляцию; привязанность проявляете остроумием и обменом идеями.') },
  ESTJ: { title: L('Kararlı organizatör', 'Decisive organizer', 'Решительный организатор'), summary: L('Düzeni kurar, süreçleri yönetir ve sonuç alırsın. Net beklentiler ve sorumluluk senin için önemlidir.', 'You set up order, run processes and get results. Clear expectations and accountability matter to you.', 'Вы наводите порядок, ведёте процессы и добиваетесь результатов. Чёткие ожидания и ответственность важны для вас.'), strengths: [L('Organizasyon ve liderlik', 'Organisation and leadership', 'Организованность и лидерство'), L('Kararlılık', 'Decisiveness', 'Решительность'), L('Güvenilirlik', 'Reliability', 'Надёжность')], growth: [L('Esneklik', 'Flexibility', 'Гибкость'), L('Farklı görüşleri dinlemek', 'Listening to different views', 'Слушать другие мнения'), L('Duygulara alan açmak', 'Making room for feelings', 'Оставлять место чувствам')], work: L('Sorumluluk, yapı ve ölçülebilir hedefler olan işlerde parlarsın.', 'You shine in roles with responsibility, structure and measurable goals.', 'Вы сильны в ролях с ответственностью, структурой и измеримыми целями.'), relationships: L('Sadık ve korumacısın; sevgini sorumluluk alarak gösterirsin.', 'You are loyal and protective; you show love by taking responsibility.', 'Вы верны и заботливы; любовь проявляете, беря на себя ответственность.') },
  ESFJ: { title: L('Sıcak koordinatör', 'Warm coordinator', 'Тёплый координатор'), summary: L('İnsanları bir araya getirir, ihtiyaçları görür ve uyumu korursun. Yardımseverliğin ve düzenin çevrene güven verir.', 'You bring people together, notice needs and keep harmony. Your helpfulness and order reassure those around you.', 'Вы объединяете людей, замечаете потребности и сохраняете гармонию. Ваша отзывчивость и порядок успокаивают окружающих.'), strengths: [L('Sosyal uyum kurma', 'Building social harmony', 'Создание социальной гармонии'), L('Pratik organizasyon', 'Practical organisation', 'Практическая организация'), L('Cömertlik', 'Generosity', 'Щедрость')], growth: [L('Onay ihtiyacını gevşetmek', 'Loosening the need for approval', 'Ослабить потребность в одобрении'), L('Eleştiriyi kişisel almamak', 'Not taking criticism personally', 'Не принимать критику на свой счёт'), L('Kendi sınırlarını korumak', 'Protecting your own limits', 'Беречь свои границы')], work: L('İş birliği, insan ilişkileri ve düzen gerektiren işlerde verimli olursun.', 'You are productive in work requiring cooperation, people skills and order.', 'Вы продуктивны в работе, требующей сотрудничества, навыков общения и порядка.'), relationships: L('Şefkatli ve ilgilisin; takdir ve karşılıklılık seni besler.', 'You are caring and attentive; appreciation and reciprocity nourish you.', 'Вы заботливы и внимательны; признательность и взаимность питают вас.') },
  ENFJ: { title: L('İlham veren rehber', 'Inspiring mentor', 'Вдохновляющий наставник'), summary: L('İnsanların potansiyelini görür ve onları büyütmeye çalışırsın. Empati ve organizasyonu birleştirirsin.', 'You see people’s potential and work to grow it. You combine empathy with organisation.', 'Вы видите потенциал людей и помогаете ему раскрыться. Вы соединяете эмпатию с организованностью.'), strengths: [L('İnsanları geliştirme', 'Developing people', 'Развитие людей'), L('İkna edici iletişim', 'Persuasive communication', 'Убедительное общение'), L('Vizyon ve düzen', 'Vision and order', 'Видение и порядок')], growth: [L('Kendine de bakmak', 'Caring for yourself too', 'Заботиться и о себе'), L('Herkesi memnun etmeye çalışmamak', 'Not trying to please everyone', 'Не стараться угодить всем'), L('Sert geri bildirimi taşımak', 'Handling harsh feedback', 'Переносить резкую критику')], work: L('Eğitim, liderlik ve insan gelişimi odaklı işlerde parlarsın.', 'You shine in teaching, leadership and people-development roles.', 'Вы сильны в обучении, лидерстве и развитии людей.'), relationships: L('Derin ve verici bağlar kurarsın; karşılıklı gelişim seni besler.', 'You build deep, giving bonds; mutual growth nourishes you.', 'Вы строите глубокие щедрые связи; взаимный рост питает вас.') },
  ENTJ: { title: L('Vizyoner lider', 'Visionary leader', 'Лидер-визионер'), summary: L('Büyük hedefler koyar, strateji kurar ve insanları harekete geçirirsin. Kararlı, doğrudan ve verimlilik odaklısın.', 'You set big goals, build strategy and mobilise people. You are decisive, direct and efficiency-minded.', 'Вы ставите большие цели, строите стратегию и мобилизуете людей. Вы решительны, прямы и ориентированы на эффективность.'), strengths: [L('Stratejik liderlik', 'Strategic leadership', 'Стратегическое лидерство'), L('Kararlılık ve hız', 'Decisiveness and pace', 'Решительность и темп'), L('Verimlilik', 'Efficiency', 'Эффективность')], growth: [L('Sabır ve dinleme', 'Patience and listening', 'Терпение и умение слушать'), L('Duyguları hesaba katmak', 'Factoring in feelings', 'Учитывать чувства'), L('Kontrolü paylaşmak', 'Sharing control', 'Делиться контролем')], work: L('Büyük hedefler, ekip yönetimi ve strateji gerektiren işlerde parlarsın.', 'You shine in roles with big goals, team leadership and strategy.', 'Вы сильны в ролях с большими целями, руководством командой и стратегией.'), relationships: L('Doğrudan ve sadıksın; sevgini birlikte büyüyerek gösterirsin.', 'You are direct and loyal; you show love by growing together.', 'Вы прямы и верны; любовь проявляете, растя вместе.') },
}

export const CLARITY_LABELS: Readonly<Record<Clarity, Localized>> = {
  balanced: L('Dengede', 'Balanced', 'Баланс'),
  slight: L('Hafif', 'Slight', 'Слабое'),
  moderate: L('Orta', 'Moderate', 'Умеренное'),
  clear: L('Belirgin', 'Clear', 'Выраженное'),
  veryClear: L('Çok belirgin', 'Very clear', 'Очень выраженное'),
}
