import { expect, test } from '@playwright/test'

test.describe('catalog', () => {
  test('lists tools, filters by search and category, and keeps state in the URL', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('h1')).toBeVisible()
    const cards = page.locator('article.tool-card')
    await expect(cards).toHaveCount(23)
    await page.getByRole('searchbox').fill('kredi')
    await expect(cards).toHaveCount(1)
    await expect(page).toHaveURL(/q=kredi/)
    await page.getByRole('button', { name: 'Aramayı temizle' }).click()
    await page.getByRole('button', { name: 'Sağlık' }).click()
    await expect(cards).toHaveCount(2)
    await expect(page).toHaveURL(/category=Sa/)
    await page.getByRole('button', { name: 'Filtreleri temizle' }).click()
    await expect(cards).toHaveCount(23)
  })

  test('promoted tools stay first, pins follow them and survive a reload', async ({ page }) => {
    await page.goto('/')
    const titles = page.locator('article.tool-card h3')
    await expect(titles.first()).toHaveText('Bileşik Faiz Hesaplama')
    await page.getByRole('button', { name: /BMI Hesaplama aracını en üste sabitle/ }).click()
    await expect(titles.nth(4)).toHaveText('BMI Hesaplama')
    await page.getByRole('combobox', { name: 'Araçları sırala' }).click()
    await page.getByRole('option', { name: 'İsim (Z–A)' }).click()
    await expect(titles.first()).toHaveText('Bileşik Faiz Hesaplama')
    await expect(titles.nth(4)).toHaveText('BMI Hesaplama')
    await expect(page).toHaveURL(/sort=name-desc/)
    await page.reload()
    await expect(titles.nth(4)).toHaveText('BMI Hesaplama')
    await page.getByRole('button', { name: /BMI Hesaplama sabitlemesini kaldır/ }).click()
    await expect(titles.nth(4)).not.toHaveText('BMI Hesaplama')
  })

  test('language toggle switches copy and is remembered', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('combobox', { name: 'Dil seçin' }).first().click()
    await page.getByRole('option', { name: 'English' }).click()
    await expect(page.locator('h1')).toContainText('Small tools')
    await page.reload()
    await expect(page.locator('h1')).toContainText('Small tools')
    await page.getByRole('link', { name: /Compound interest calculator — open tool/ }).click()
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Compound interest calculator')
    await page.getByRole('combobox', { name: 'Choose language' }).first().click()
    await page.getByRole('option', { name: 'Русский' }).click()
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Калькулятор сложных процентов')
    await page.getByRole('combobox', { name: 'Выберите язык' }).first().click()
    await page.getByRole('option', { name: 'Türkçe' }).click()
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Bileşik Faiz Hesaplama')
  })

  test('legacy Turkish slugs redirect permanently', async ({ request }) => {
    const response = await request.get('/tools/faiz-hesaplama', { maxRedirects: 0 })
    expect(response.status()).toBe(308)
    expect(response.headers().location).toContain('/tools/compound-interest-calculator')
  })
})

test('contact page pre-fills the topic and builds a mailto link', async ({ page }) => {
  await page.goto('/contact?topic=bug')
  await expect(page.getByRole('combobox', { name: 'Konu' })).toHaveText('Hata bildirimi')
  await page.getByLabel('Mesaj').fill('Kısa')
  await page.getByRole('button', { name: 'E-posta uygulamasında aç' }).click()
  const formAlerts = page.locator('#contact-form').getByRole('alert')
  await expect(formAlerts).toContainText('en az 10 karakter')
  await page.getByLabel('Mesaj').fill('Yüzde aracında virgül ile ondalık girince sonuç boş kalıyor.')
  await expect(formAlerts).toHaveCount(0)
})
