import { expect, test } from '@playwright/test'

test.describe('tool history', () => {
  test('saves, restores, deletes and never resurrects deleted queries', async ({ page }) => {
    await page.goto('/tools/loan-calculator')
    const amount = page.getByLabel('Kredi tutarı')
    await amount.fill('250000')
    await page.waitForTimeout(1500)
    await amount.fill('300000')
    await page.waitForTimeout(1500)
    const toggle = page.getByRole('button', { name: /Son sorgular/ })
    await expect(toggle).toContainText('2/10')
    await toggle.click()
    const items = page.locator('.history-item')
    await expect(items).toHaveCount(2)
    await expect(items.first()).toContainText('300000')
    await items.first().getByRole('button', { name: 'Kaydı sil' }).click()
    await expect(items).toHaveCount(1)
    await amount.fill('400000')
    await page.waitForTimeout(1500)
    await expect(items).toHaveCount(2)
    await expect(page.locator('.history-item', { hasText: '300000' })).toHaveCount(0)
    await page.locator('.history-item', { hasText: '250000' }).getByRole('button', { name: 'Bu sorguyu geri yükle' }).click()
    await expect(amount).toHaveValue('250000')
    await page.reload()
    await expect(page.getByRole('button', { name: /Son sorgular/ })).toContainText('2/10')
    await page.getByRole('button', { name: /Son sorgular/ }).click()
    await page.getByRole('button', { name: 'Tümünü sil' }).click()
    await expect(page.getByRole('button', { name: /Son sorgular/ })).toContainText('0/10')
  })

  test('history is separate per tool and includes the conversion rate field', async ({ page }) => {
    await page.goto('/tools/loan-calculator')
    await page.getByLabel('Dönüşüm oranı').fill('0.03')
    await page.waitForTimeout(1500)
    const stored = await page.evaluate(() => localStorage.getItem('tools:history:v2:loan-calculator') ?? '')
    expect(stored).toContain('"conversion":"0.03"')
    expect(stored).not.toContain('Dönüşüm')
    await page.getByLabel('Dönüşüm oranı').fill('0.05')
    await page.waitForTimeout(1500)
    await page.getByRole('button', { name: /Son sorgular/ }).click()
    await page.locator('.history-item').nth(1).getByRole('button', { name: 'Bu sorguyu geri yükle' }).click()
    await expect(page.getByLabel('Dönüşüm oranı')).toHaveValue('0.03')
    await page.goto('/tools/vat-calculator')
    await expect(page.getByRole('button', { name: /Son sorgular/ })).toContainText('0/10')
  })
})

test.describe('inputs', () => {
  test('long selects are searchable and scroll to the chosen year', async ({ page }) => {
    await page.goto('/tools/monthly-inflation-rates')
    await page.getByRole('combobox', { name: 'Yıl' }).click()
    await page.getByRole('searchbox', { name: 'Seçeneklerde ara' }).fill('199')
    await expect(page.getByRole('option')).toHaveCount(10)
    await page.getByRole('option', { name: '1994' }).click()
    await expect(page.getByRole('combobox', { name: 'Yıl' })).toHaveText('1994')
    await expect(page.locator('table tbody tr')).toHaveCount(12)
    await expect(page.locator('table tbody tr').first()).toContainText('%')
  })

  test('date fields validate real calendar dates and drive results', async ({ page }) => {
    await page.goto('/tools/age-calculator')
    const day = page.getByLabel('Doğum tarihi: gün')
    await day.fill('31')
    await page.getByRole('combobox', { name: 'Doğum tarihi: ay' }).click()
    await page.getByRole('option', { name: 'Şubat' }).click()
    await expect(page.getByRole('alert').filter({ hasText: 'gerçek bir tarih' })).toHaveCount(1)
    await day.fill('29')
    await page.getByLabel('Doğum tarihi: yıl').fill('2000')
    await expect(page.getByRole('alert').filter({ hasText: 'gerçek bir tarih' })).toHaveCount(0)
    await expect(page.getByText(/yıl$/).first()).toBeVisible()
  })
})

test.describe('personality test', () => {
  test('walks through all sections and shows a typed result', async ({ page }) => {
    await page.goto('/tools/mbti-personality-test')
    await page.getByRole('button', { name: 'Teste başla' }).click()
    for (let section = 0; section < 4; section += 1) {
      const choices = page.locator('label', { has: page.getByRole('radio', { name: 'Kesinlikle sol' }) })
      await expect(choices).toHaveCount(8)
      for (let index = 0; index < 8; index += 1) await choices.nth(index).click()
      await expect(page.getByRole('radio', { name: 'Kesinlikle sol', checked: true })).toHaveCount(8)
      await page.getByRole('button', { name: section === 3 ? 'Sonucu gör' : 'Sonraki bölüm' }).click()
    }
    await expect(page.getByText('Yaklaşık tipin')).toBeVisible()
    await expect(page.locator('.mbti-type-large .mbti-slot')).toHaveCount(4)
    await expect(page.getByText('Boyutlara göre tercih gücü')).toBeVisible()
  })
})

test.describe('finance', () => {
  test('salary tool switches countries and inverts net to gross', async ({ page }) => {
    await page.goto('/tools/salary-calculator')
    await expect(page.getByText('Ocak neti')).toBeVisible()
    await page.getByRole('combobox', { name: 'Ülke / model' }).click()
    await page.getByRole('option', { name: /United States|ABD/ }).click()
    await expect(page.getByLabel('Eyalet + yerel vergi')).toBeVisible()
    await page.getByRole('button', { name: 'Netten brüte' }).click()
    await page.getByLabel('Hedef aylık net maaş').fill('4000')
    await expect(page.getByText('Gerekli aylık brüt maaş')).toBeVisible()
  })

  test('historical investment calculator supports deposits with withholding', async ({ page }) => {
    await page.goto('/tools/historical-investment-calculator')
    await page.getByRole('combobox', { name: 'Varlık' }).click()
    await page.getByRole('option', { name: /mevduat/i }).click()
    await expect(page.getByLabel('Faiz stopajı')).toHaveValue('15')
    await expect(page.getByText('Dönem ort. yıllık faiz')).toBeVisible()
    await expect(page.locator('.line-chart svg')).toBeVisible()
  })
})

test.describe('growth calculators', () => {
  test('compound, savings and investment pages share one form with different presets', async ({ page }) => {
    await page.goto('/tools/compound-interest-calculator')
    await expect(page.getByRole('button', { name: 'Bileşik Faiz', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByLabel('Düzenli katkı')).toHaveCount(0)
    await expect(page.getByText(/sonra toplam değer/)).toBeVisible()
    await page.goto('/tools/savings-calculator')
    await expect(page.getByRole('button', { name: 'Tasarruf', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByLabel('Düzenli katkı')).toBeVisible()
    await page.goto('/tools/investment-calculator')
    await expect(page.getByRole('button', { name: 'Yatırım', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('combobox', { name: 'Bileşik sıklığı' })).toBeVisible()
    await page.getByRole('button', { name: 'Tasarruf', exact: true }).click()
    await expect(page).toHaveURL(/savings-calculator/)
    await page.getByRole('switch', { name: /Gerçek geçmiş verilerle hesapla/ }).click()
    await expect(page.getByRole('combobox', { name: 'Varlık' })).toBeVisible()
    await expect(page).toHaveURL(/historical-investment-calculator/)
  })

  test('historical mode can contribute in another currency', async ({ page }) => {
    await page.goto('/tools/historical-investment-calculator')
    await expect(page.getByRole('combobox', { name: 'Varlık' })).toBeVisible()
    await page.getByRole('switch', { name: 'Gelişmiş para birimi seçenekleri' }).click()
    await page.getByRole('combobox', { name: 'Katkı para birimi' }).click()
    await page.getByRole('option', { name: /US dollar|Amerikan doları/ }).click()
    await page.getByLabel('Düzenli katkı').fill('100')
    await expect(page.getByText(/USD → TRY/)).toBeVisible()
    await expect(page.getByText(/her ay \$100/)).toBeVisible()
  })

  test('the inflation toggle adds real values for projections and history', async ({ page }) => {
    await page.goto('/tools/investment-calculator')
    await expect(page.getByText('Enflasyon kaybı')).toHaveCount(0)
    await page.getByRole('switch', { name: /Enflasyonu hesaba kat/ }).click()
    await expect(page.getByRole('combobox', { name: 'Enflasyon verisi ülkesi' })).toHaveText(/Türkiye/)
    const rate = page.getByLabel('Tahmini enflasyon (TRY)')
    await expect(rate).not.toHaveValue('')
    await expect(page.getByText('Enflasyon kaybı').first()).toBeVisible()
    await expect(page.getByText('Reel yıllık getiri')).toBeVisible()
    await rate.fill('0')
    await expect(page.getByText(/yatırım enflasyonu yeniyor/)).toBeVisible()
    await page.getByRole('combobox', { name: 'Enflasyon verisi ülkesi' }).click()
    await page.getByRole('option', { name: /ABD/ }).click()
    await expect(rate).not.toHaveValue('0')
    await page.getByRole('switch', { name: /Gerçek geçmiş verilerle hesapla/ }).click()
    await expect(page.getByText('Reel kâr / zarar')).toBeVisible()
    await expect(page.getByLabel('Tahmini enflasyon (TRY)')).toHaveCount(0)
    await page.getByRole('switch', { name: /Enflasyonu hesaba kat/ }).click()
    await expect(page.getByText('Reel kâr / zarar')).toHaveCount(0)
  })

  test('result tables switch between yearly totals and one year of months', async ({ page }) => {
    await page.goto('/tools/savings-calculator')
    await expect(page.getByRole('tab', { name: 'Yıllık' })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('cell', { name: 'Toplam', exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Aylık' }).click()
    await expect(page.getByRole('button', { name: '5. yıl', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('cell', { name: '5. yıl toplamı' })).toBeVisible()
    await page.getByRole('button', { name: '2. yıl', exact: true }).click()
    await expect(page.getByRole('cell', { name: '13. ay', exact: true })).toBeVisible()
    await page.getByRole('combobox', { name: 'Yıl seç' }).click()
    await page.getByRole('option', { name: '4. yıl' }).click()
    await expect(page.getByRole('cell', { name: '4. yıl toplamı' })).toBeVisible()
    await page.getByRole('switch', { name: /Gerçek geçmiş verilerle hesapla/ }).click()
    await expect(page.getByRole('tab', { name: 'Aylık' })).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('button', { name: 'Önceki yıl' }).click()
    await expect(page.getByRole('cell', { name: /^2025 toplamı$/ })).toBeVisible()
  })

  test('projections can contribute in another currency along an inflation-based rate path', async ({ page }) => {
    await page.goto('/tools/investment-calculator')
    await page.getByRole('switch', { name: 'Gelişmiş para birimi seçenekleri' }).click()
    await page.getByRole('combobox', { name: 'Katkı para birimi' }).click()
    await page.getByRole('option', { name: /Amerikan doları/ }).click()
    const rate = page.getByLabel('Bugünkü kur')
    const rateValue = Number(await rate.inputValue())
    expect(rateValue).toBeGreaterThan(30)
    const lira = page.getByLabel('Tahmini enflasyon (TRY)')
    const dollar = page.getByLabel('Tahmini enflasyon (USD)')
    expect(Number(await lira.inputValue())).toBeGreaterThan(15)
    expect(Number(await dollar.inputValue())).toBeGreaterThan(1)
    await expect(page.getByText(/Kur tahmini/)).toBeVisible()
    await expect(page.getByText(/\$60\.000/).first()).toBeVisible()
    await page.getByRole('tab', { name: 'Aylık' }).click()
    await expect(page.getByRole('columnheader', { name: 'Kur' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Katkı (USD)' })).toBeVisible()
    await page.getByRole('group', { name: 'Oran birimi' }).getByRole('button', { name: 'Aylık' }).click()
    const monthly = Number(await lira.inputValue())
    expect(monthly).toBeGreaterThan(0.5)
    expect(monthly).toBeLessThan(5)
    await lira.fill('3')
    await expect(page.getByText(/↺ 10 yıl ort\./)).toBeVisible()
    await page.getByRole('switch', { name: /Enflasyonu hesaba kat/ }).click()
    await expect(page.getByText('Enflasyon kaybı').first()).toBeVisible()
  })
})

test.describe('leave planner', () => {
  test('bridges Turkish holidays, follows the weekly days off and offers regions where needed', async ({ page }) => {
    await page.goto('/tools/leave-planner')
    await expect(page.getByText(/gün tatil$/).first()).toBeVisible()
    await expect(page.locator('.stretch-card').first()).toBeVisible()
    await expect(page.locator('.leave-month').first()).toBeVisible()
    await expect(page.locator('.leave-day.is-leave').first()).toBeVisible()
    await page.getByLabel('İzin günü sayısı').fill('2')
    await expect(page.getByText(/2 izin günüyle/)).toBeVisible()
    await expect(page.locator('.leave-day.is-leave')).toHaveCount(2)
    await page.getByRole('group', { name: 'Haftalık tatil günleri' }).getByRole('button', { name: 'Cmt' }).click()
    await expect(page.getByRole('group', { name: 'Haftalık tatil günleri' }).getByRole('button', { name: 'Cmt' })).toHaveAttribute('aria-pressed', 'false')
    await expect(page.locator('.leave-day.is-leave')).toHaveCount(2)
    await page.getByRole('button', { name: 'En uzun tek tatil' }).click()
    await expect(page.getByText(/1 tatil bloğu/)).toBeVisible()
    await page.getByRole('combobox', { name: 'Ülke' }).click()
    await page.getByRole('option', { name: /Birleşik Krallık/ }).click()
    await expect(page.getByRole('combobox', { name: 'Bölge' })).toHaveText(/İngiltere/)
  })
})
